### ISSUE TITLE
Django Extensions Change

### ISSUE THREAD

**Issue by JREAM** [dansackett/django-project-template#6]
Namespace Change **.db** added , leaving note or Ill do it soon.

Change:
```
from django_extensions.models import TimeStampedModel, TitleSlugDescriptionModel
```
To:
```
from django_extensions.db.models import TimeStampedModel, TitleSlugDescriptionModel
```

**Comment by dansackett** [comment]
That is not used in this starter template. The only model is the auth user. It must be something you're using in your own project.
